/**
 * Cloudflare Worker runtime bindings.
 *
 * Generated by `wrangler types`; the source of truth is
 * `apps/worker/wrangler.jsonc`. Re-run `bunx wrangler types` after every
 * binding or var change.
 */
export type CloudflareBindings = Cloudflare.Env;
