/**
 * Modal opened when a SUSPENDED_HITL card drops on the ACTIONED
 * column. Reuses `ActionForm` so the inline action panel and the
 * board-drag path produce identical POSTs against
 * `POST /api/cases/:id/action`.
 *
 * `actionId` is generated by the drop handler (at `onDragEnd`) and
 * passed in as a prop so closing + re-opening the modal for the same
 * drag preserves idempotency. A fresh drag creates a fresh actionId.
 */
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import type { ReviewerActionRequest } from "@mizan/shared";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog.tsx";
import { ActionForm } from "@/components/case/action-form.tsx";
import { ReviewerActionError, submitReviewerAction } from "@/lib/cases-api.ts";
import { queryKeys } from "@/lib/query-keys.ts";
import { COPY } from "@/lib/copy-constants.ts";

interface KanbanActionModalProps {
  readonly caseId: string | null;
  readonly actionId: string | null;
  readonly open: boolean;
  readonly onOpenChange: (next: boolean) => void;
}

function describeError(error: unknown): string {
  if (!(error instanceof ReviewerActionError)) {
    return error instanceof Error ? error.message : "Action failed";
  }
  switch (error.code) {
    case "not_suspended_or_claimed":
      return "Another reviewer acted on this case";
    case "not_found":
      return "Case not found";
    case "no_run":
      return "Case has no active workflow run";
    case "workflow_failed":
      return "Workflow failed to resume — try again";
  }
}

export function KanbanActionModal({
  caseId,
  actionId,
  open,
  onOpenChange,
}: KanbanActionModalProps): React.JSX.Element {
  const queryClient = useQueryClient();
  const mutation = useMutation({
    mutationFn: (body: ReviewerActionRequest) => {
      if (!caseId) return Promise.reject(new Error("missing caseId"));
      return submitReviewerAction(caseId, body);
    },
    onSuccess: async () => {
      toast.success("Action recorded");
      onOpenChange(false);
      if (caseId) {
        await queryClient.invalidateQueries({ queryKey: queryKeys.cases.detail(caseId) });
      }
      await queryClient.invalidateQueries({ queryKey: queryKeys.cases.all });
    },
    onError: (error) => {
      toast.error(describeError(error));
    },
  });
  const formLocked = mutation.isPending || mutation.isSuccess;
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg space-y-4">
        <DialogHeader className="space-y-2 border-b border-border/40 pb-4">
          <div className="text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
            Reviewer decision · audit-logged
          </div>
          <DialogTitle className="text-xl font-semibold tracking-tight">{COPY.modal.title}</DialogTitle>
          <DialogDescription>{COPY.modal.description}</DialogDescription>
        </DialogHeader>
        {caseId && actionId ? (
          <ActionForm
            key={actionId}
            pending={formLocked}
            onSubmit={async (body) => {
              await mutation.mutateAsync({ ...body, action_id: actionId });
            }}
          />
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
