/**
 * Live brief stream — wires `useChat` against the worker's Mode A
 * SSE endpoint at `POST /api/cases/:id/brief`. The worker reads its
 * inputs from URL params + producer-guard context (see
 * `apps/worker/src/routes/cases.ts:32-66`), so the canonical
 * stream-open trigger is `sendMessage({ text: '' })` on mount —
 * the empty payload is intentional, do NOT "fix" it.
 *
 * On `onFinish` we invalidate the case detail query so the parent
 * route re-fetches the persisted brief + flipped status. The
 * derived view (text, tools, steps) is folded each render via
 * `foldParts(messages.parts)` so component state remains a pure
 * function of the streamed parts.
 *
 * Resume / in-flight handling: when the case is already RUNNING
 * from a prior POST (Mode B consumer started it, or another
 * reviewer tab opened the page first), the worker's producer guard
 * returns 409 with `{ "error": "case already running" }`. That is
 * NOT a failure — the brief is being generated by another stream
 * we cannot attach to in Phase 6 (full SSE resume + GET stream-by-id
 * lands in Phase 7's `workflow_events` catch-up endpoint). Until
 * then, this component detects that specific shape and shows an
 * in-progress notice + polls the case-detail query so the surface
 * flips to the persisted brief the moment the other stream finishes.
 */
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";
import { useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useRef } from "react";
import { Loader2 } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert.tsx";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card.tsx";
import { queryKeys } from "@/lib/query-keys.ts";
import { BriefCopy } from "./copy.tsx";
import { ExtractionCard } from "./extraction-card.tsx";
import { StepProgress } from "./step-progress.tsx";
import { foldParts } from "./stream-parts.ts";

interface BriefStreamProps {
  readonly caseId: string;
}

const ALREADY_RUNNING_RE = /case already running/i;
const POLL_INTERVAL_MS = 5_000;
const POLL_MAX_TICKS = 120;

function StreamError({ message }: { readonly message: string }): React.JSX.Element {
  return (
    <Alert variant="destructive">
      <AlertTitle>Brief stream failed</AlertTitle>
      <AlertDescription>{message}</AlertDescription>
    </Alert>
  );
}

function InFlightNotice(): React.JSX.Element {
  return (
    <Card className="border-border/80 shadow-elev-1">
      <CardHeader className="flex flex-row items-center gap-2 space-y-0">
        <Loader2 className="size-4 animate-spin text-status-info-foreground" />
        <CardTitle className="text-sm font-medium">Composing brief</CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-muted-foreground">
          Another session is already running the workflow for this case. The brief will appear
          here automatically when it finishes — no need to refresh.
        </p>
      </CardContent>
    </Card>
  );
}

function streamApi(caseId: string): string {
  return `/api/cases/${caseId}/brief`;
}

/**
 * Mode A SSE transport.
 *
 * `prepareSendMessagesRequest` returns an empty body — the worker
 * (`apps/worker/src/routes/cases.ts:32-66`) reads inputs from URL
 * params + producer-guard context and does NOT consume the request
 * body. Sending an empty `{}` matches that contract exactly; the AI
 * SDK 6 default would otherwise wrap the (empty) message in
 * `{ messages: [...] }` which the worker would silently discard but
 * is wasted bytes. `Accept: text/event-stream` matches the worker's
 * `wantsEventStream(c)` content negotiation in
 * `apps/worker/src/routes/cases.ts:33`.
 */
function buildTransport(caseId: string) {
  return new DefaultChatTransport({
    api: streamApi(caseId),
    headers: { Accept: "text/event-stream" },
    prepareSendMessagesRequest: () => ({ body: {} }),
  });
}

/**
 * Pins `sendMessage` to one POST per `caseId` mount. React 19
 * StrictMode mounts effects twice in dev; firing twice would race
 * the worker's producer guard.
 */
function useStreamOpener(caseId: string, sendMessage: (input: { text: string }) => void): void {
  const openedFor = useRef<string | null>(null);
  useEffect(() => {
    if (openedFor.current === caseId) return;
    openedFor.current = caseId;
    sendMessage({ text: "" });
  }, [caseId, sendMessage]);
}

/**
 * Polls the case-detail query on a fixed interval. Stop-gap for the
 * "case already running" path. PRD Phase 7 (`docs/prd.md` lines
 * 743–808) replaces it with the SSE-native `Last-Event-ID` catch-up
 * pattern over the `workflow_events` D1 table:
 *
 *   POST handler — each Mastra step lifecycle (start / finish /
 *     suspend / resume) writes a row to `workflow_events` with a
 *     monotonic id; SSE emits `id:` headers per chunk.
 *
 *   GET `/api/cases/:id/brief/stream` — reads the request's
 *     `Last-Event-ID` header, replays every `workflow_events` row
 *     for that runId with id > Last-Event-ID, then attaches to the
 *     live workflow stream. Returns 204 when the run is terminal.
 *
 *   Client — `useChat({ id, resume: true, transport })` + AI SDK 6's
 *     EventSource Last-Event-ID semantics (PRD §7 line 759 force-read).
 *     Drops `useCasePoll` entirely.
 *
 * No Durable Object needed — D1 row replay is the canonical CF
 * pattern for SSE catch-up per PRD §7.9 (line 750). `Mastra
 * run.resumeStream()` is the orthogonal HITL `.suspend()`/`.resume()`
 * concern (line 800) — different from SSE network reconnect.
 *
 * Interval is capped at `POLL_MAX_TICKS * POLL_INTERVAL_MS` (10 min)
 * so a stalled workflow can't accumulate fetches indefinitely.
 */
function useCasePoll(caseId: string, enabled: boolean): void {
  const queryClient = useQueryClient();
  useEffect(() => {
    if (!enabled) return;
    let ticks = 0;
    const handle = setInterval(() => {
      ticks += 1;
      if (ticks > POLL_MAX_TICKS) {
        clearInterval(handle);
        return;
      }
      void queryClient.invalidateQueries({
        queryKey: queryKeys.cases.detail(caseId),
        refetchType: "all",
      });
    }, POLL_INTERVAL_MS);
    return () => clearInterval(handle);
  }, [caseId, enabled, queryClient]);
}

function isAlreadyRunning(message: string): boolean {
  return ALREADY_RUNNING_RE.test(message);
}

export function BriefStream({ caseId }: BriefStreamProps): React.JSX.Element {
  const queryClient = useQueryClient();
  const transport = useMemo(() => buildTransport(caseId), [caseId]);
  const { messages, sendMessage, error, status } = useChat({
    id: `case-${caseId}`,
    transport,
    onFinish: async () => {
      await queryClient.invalidateQueries({
        queryKey: queryKeys.cases.detail(caseId),
        refetchType: "all",
      });
    },
  });

  useStreamOpener(caseId, (input) => {
    void sendMessage(input);
  });

  const assistantParts = useMemo(
    () => messages.flatMap((message) => (message.role === "assistant" ? message.parts : [])),
    [messages],
  );
  const view = useMemo(() => foldParts(assistantParts), [assistantParts]);
  const fatalMessage = error?.message ?? (status === "error" ? "Stream closed unexpectedly" : null);
  const inflight =
    (view.errorText !== null && isAlreadyRunning(view.errorText)) ||
    (fatalMessage !== null && isAlreadyRunning(fatalMessage));

  useCasePoll(caseId, inflight);

  if (inflight) return <InFlightNotice />;

  return (
    <div className="space-y-4">
      <StepProgress steps={view.steps} />
      {view.tools.length > 0 ? (
        <div className="space-y-2">
          {view.tools.map((tool) => (
            <ExtractionCard key={tool.id} tool={tool} />
          ))}
        </div>
      ) : null}
      <BriefCopy markdown={view.text} />
      {view.errorText ? <StreamError message={view.errorText} /> : null}
      {fatalMessage ? <StreamError message={fatalMessage} /> : null}
    </div>
  );
}
