/**
 * Side drawer showing the full clause body for a citation chip.
 * Fetches `/api/policy/clauses/:id?source=...` on first open via
 * `usePolicyClause`. Errors fall back to a "not found" state with a
 * copy-clause-ID button.
 */
import { Copy, Loader2 } from "lucide-react";
import { toast } from "sonner";
import type { PolicyClauseSource } from "@mizan/shared";
import { Button } from "@/components/ui/button.tsx";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet.tsx";
import { usePolicyClause } from "@/hooks/use-policy-clause.ts";
import { COPY } from "@/lib/copy-constants.ts";

interface CitationDrawerProps {
  readonly clauseId: string;
  readonly source: PolicyClauseSource;
  readonly open: boolean;
  readonly onOpenChange: (next: boolean) => void;
}

function sourceLabel(source: PolicyClauseSource): string {
  return source === "zakat" ? COPY.citations.sourceZakat : COPY.citations.sourceSafety;
}

function NotFound({ clauseId }: { readonly clauseId: string }): React.JSX.Element {
  const onCopy = async (): Promise<void> => {
    await navigator.clipboard.writeText(clauseId);
    toast.success("Clause ID copied");
  };
  return (
    <div className="space-y-3 text-sm">
      <p className="text-muted-foreground">{COPY.citations.drawerNotFound}</p>
      <Button variant="outline" size="sm" onClick={() => void onCopy()}>
        <Copy className="mr-2 size-3.5" />
        {COPY.citations.drawerCopyClauseId}
      </Button>
    </div>
  );
}

export function CitationDrawer({
  clauseId,
  source,
  open,
  onOpenChange,
}: CitationDrawerProps): React.JSX.Element {
  const query = usePolicyClause(clauseId, source, open);
  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="flex w-full max-w-md flex-col gap-5 overflow-y-auto sm:max-w-md">
        <SheetHeader className="space-y-3 text-left">
          <div className="flex items-center justify-between gap-2 text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
            <span>{sourceLabel(source)}</span>
            <span className="font-mono text-foreground/80 tabular">{clauseId}</span>
          </div>
          <SheetTitle className="text-xl font-semibold tracking-tight">
            {query.data?.title ?? COPY.citations.drawerTitle}
          </SheetTitle>
          <SheetDescription className="text-xs text-muted-foreground">
            Full clause body - verified against the bundled corpus, not regenerated by AI.
          </SheetDescription>
        </SheetHeader>
        {query.isPending ? (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin" />
            {COPY.documents.loadingLabel}
          </div>
        ) : null}
        {query.isError ? <NotFound clauseId={clauseId} /> : null}
        {query.data ? (
          <div className="animate-rise space-y-4 border-l-2 border-foreground/15 pl-4">
            <p className="whitespace-pre-wrap text-[14px] leading-relaxed text-foreground">
              {query.data.body}
            </p>
            <p className="text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
              {COPY.citations.drawerVersionLabel}: {query.data.corpusVersion}
            </p>
          </div>
        ) : null}
      </SheetContent>
    </Sheet>
  );
}
